// src/connect-example/ConnectExample.jsx
function ConnectExample(props) {
  return (
    <section>
      <h2>Wallet connection</h2>
      <p>This is a sample usage of the <code>&lt;arn-connect&gt;</code> ARN component:</p>
      <arn-connect>
        <button slot="if-false">{props.connectMsg}</button>
        <button slot="if-true">{props.disconnectMsg}</button>
      </arn-connect>
    </section>
  )
}

export default ConnectExample

// src/lib/ConnectExample.svelte
<section>
  <h2>Wallet connection</h2>
  <p>This is a sample usage of the <code>&lt;arn-connect&gt;</code> ARN component:</p>
  <arn-connect>
    <button slot="if-false">{connectMsg}</button>
    <button slot="if-true">{disconnectMsg}</button>
  </arn-connect>
</section>

<script>
  export let connectMsg, disconnectMsg;
</script>
