// src/app.jsx
import ConnectExample from "./connect-example/ConnectExample.jsx"
import IfConnectedExample from "./connect-example/IfConnectedExample.jsx"

export function App() {

  return (
    <>
      <h1>ARN example</h1>
      <p>This is a React (built by Vite) version of the ARN example.</p>
      <ConnectExample connectMsg='Connect your wallet' disconnectMsg='Disconnect your wallet'/>
      <IfConnectedExample connectedMsg='You are connected!' disconnectedMsg='You are disconnected.'/>
    </>
  )
}

// src/App.svelte
<script>
  import ConnectExample from "./lib/ConnectExample.svelte"
  import IfConnectedExample from "./lib/IfConnectedExample.svelte"
</script>

<main>
  <h1>ARN Example</h1>
  <p>This is a Svelte (built by Vite) version of the ARN example.</p>
  <ConnectExample connectMsg="Connect your wallet" disconnectMsg="Disconnect your wallet"></ConnectExample>
  <IfConnectedExample connectedMsg="You are connected!" disconnectedMsg="You are disconnected."></IfConnectedExample>
</main>
