// src/app/app.component.ts
import { Component } from '@angular/core';
import { ArnClient } from '@arianee/arn-client';

declare const arnClient: ArnClient;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  version = arnClient.version
}

<h1>ARN Example</h1>
<p>This is an Angular version of the ARN example.</p>
<section>
  <h2>Wallet connection</h2>
  <p>This is a sample usage of the <code>&lt;arn-connect&gt;</code> ARN component:</p>
  <arn-connect>
    <button slot="if-false">Connect your wallet</button>
    <button slot="if-true">Disconnect your wallet</button>
  </arn-connect>
</section>
<section>
  <h2>Connection gating</h2>
  <p>This is a sample usage of the <code>&lt;arn-if-connected&gt;</code> ARN component:</p>
  <arn-if-connected>
    <p slot="if-false">You are not connected.</p>
    <p slot="if-true">Your are connected!</p>
  </arn-if-connected>
</section>

// src/App.jsx
import ConnectExample from "./connect-example/ConnectExample.jsx"
import IfConnectedExample from "./connect-example/IfConnectedExample.jsx"

function App() {
  return (
    <div className="App">
      <h1>ARN example</h1>
      <p>This is a React (built by Vite) version of the ARN example.</p>
      <ConnectExample connectMsg='Connect your wallet' disconnectMsg='Disconnect your wallet'/>
      <IfConnectedExample connectedMsg='You are connected!' disconnectedMsg='You are disconnected.'/>
    </div>
  )
}

export default App
